### ISSUE TITLE
Ability to See Pilot Hours as Admin

### ISSUE THREAD

**Issue by samdog2727** [va-net/flare#225]
**Is your feature request related to a problem? Please describe.**
As an administrator, it is helpful to be able to see the hours that a pilot currently has.

**Describe the solution you'd like**
The ability to see the total hours that a pilot has when looking at their profile in the User Management section of Administration

**Describe alternatives you've considered**
Asking the pilot I guess but that does not really work.

**Additional context**
Another administrator brought up this issue. I have not personally had this issue happen because I haven't had any of my members log flights.

**Comment by Velocity23** [comment]
Fixed in 19

**Comment by samdog2727** [comment]
@Velocity23 , now I can see how many hours they have received on Flare but this does not take into account transferred hours. I assume this is an easy fix?

**Comment by rebal15** [comment]
Yep, easy fix, I'll make an issue and do it now @samdog2727

**Comment by Velocity23** [comment]
Fixed properly in 20

**Comment by samdog2727** [comment]
Still not fixed 
![Screen Shot 2020-10-28 at 11 47 40 AM](https://user-images.githubusercontent.com/71337097/97460706-6422b000-1913-11eb-97cf-2f7447b4689e.png)

**Comment by samdog2727** [comment]
@Velocity23 ^

**Comment by Velocity23** [comment]
Properly fixed for 21
